// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview A flow for generating smart CTA texts for a landing page, based on successful patterns and A/B testing data.
 *
 * - generateSmartCTAs - A function that generates alternative CTA texts.
 * - GenerateSmartCTAsInput - The input type for the generateSmartCTAs function.
 * - GenerateSmartCTAsOutput - The return type for the generateSmartCTAs function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateSmartCTAsInputSchema = z.object({
  currentCTAText: z
    .string()
    .describe('The current CTA text used on the landing page.'),
  landingPageSegment: z
    .string()
    .describe(
      'The segment of the audience the landing page is targeting (e.g., obra privada, obra civil, desarrolladores de vivienda).' 
    ),
  conversionRate: z
    .number()
    .describe(
      'The current conversion rate of the landing page (e.g., 0.05 for 5%).'
    ),
  abTestingData: z
    .string()
    .optional()
    .describe(
      'Optional data from A/B testing, providing insights into which CTA texts performed better.  If not provided, the LLM will use general best practices.'
    ),
});
export type GenerateSmartCTAsInput = z.infer<typeof GenerateSmartCTAsInputSchema>;

const GenerateSmartCTAsOutputSchema = z.object({
  suggestedCTATexts: z
    .array(z.string())
    .describe(
      'An array of suggested CTA texts for the landing page, designed to improve conversion rates.'
    ),
  rationale: z
    .string()
    .describe(
      'A brief explanation of why each suggested CTA text is expected to perform well, based on the input data and marketing best practices.'
    ),
});
export type GenerateSmartCTAsOutput = z.infer<typeof GenerateSmartCTAsOutputSchema>;

export async function generateSmartCTAs(input: GenerateSmartCTAsInput): Promise<GenerateSmartCTAsOutput>
{
  return generateSmartCTAsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateSmartCTAsPrompt',
  input: {
    schema: GenerateSmartCTAsInputSchema,
  },
  output: {
    schema: GenerateSmartCTAsOutputSchema,
  },
  prompt: `You are an expert marketing consultant specialized in conversion rate optimization for the construction industry in Mexico.  You are helping Siento44 Construcciones improve the conversion rate of their landing page.

  Given the current CTA text, the target audience segment, the current conversion rate, and any available A/B testing data, suggest three alternative CTA texts that are likely to improve conversion rates.  Also, provide a brief rationale for each suggestion.

  Current CTA Text: {{{currentCTAText}}}
  Target Audience Segment: {{{landingPageSegment}}}
  Current Conversion Rate: {{{conversionRate}}}
  A/B Testing Data: {{{abTestingData}}}

  Ensure that the suggested CTA's align with Siento44's key messaging of trust, tranquility, and professionalism, while also appealing to the specific needs and concerns of the target audience segment.

  Output the suggested CTA texts in an array called suggestedCTATexts, and the rationales in a field called rationale.
`,
});

const generateSmartCTAsFlow = ai.defineFlow(
  {
    name: 'generateSmartCTAsFlow',
    inputSchema: GenerateSmartCTAsInputSchema,
    outputSchema: GenerateSmartCTAsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);

